import { X, Download, FileJson, Package } from "lucide-react";
import type { DesignSystem } from "@/types";

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  designSystem: DesignSystem;
}

export function ExportModal({ isOpen, onClose, designSystem }: ExportModalProps) {
  if (!isOpen) return null;

  const generateFigmaVariables = () => {
    const { primaryColor, secondaryColor, neutralColor, successColor, warningColor, errorColor, baseSpacing, baseFontSize, borderRadius } = designSystem;
    return JSON.stringify({
      collections: [
        {
          name: designSystem.projectName,
          modes: ['Light', 'Dark'],
          variables: [
            { name: 'color/primary', type: 'COLOR', value: primaryColor },
            { name: 'color/secondary', type: 'COLOR', value: secondaryColor },
            { name: 'color/neutral', type: 'COLOR', value: neutralColor },
            { name: 'color/success', type: 'COLOR', value: successColor },
            { name: 'color/warning', type: 'COLOR', value: warningColor },
            { name: 'color/error', type: 'COLOR', value: errorColor },
            { name: 'spacing/base', type: 'FLOAT', value: baseSpacing },
            { name: 'spacing/xs', type: 'FLOAT', value: baseSpacing * 0.5 },
            { name: 'spacing/sm', type: 'FLOAT', value: baseSpacing },
            { name: 'spacing/md', type: 'FLOAT', value: baseSpacing * 2 },
            { name: 'spacing/lg', type: 'FLOAT', value: baseSpacing * 3 },
            { name: 'spacing/xl', type: 'FLOAT', value: baseSpacing * 4 },
            { name: 'spacing/2xl', type: 'FLOAT', value: baseSpacing * 6 },
            { name: 'font/size/base', type: 'FLOAT', value: baseFontSize },
            { name: 'font/size/sm', type: 'FLOAT', value: Math.round(baseFontSize / designSystem.typeScaleRatio) },
            { name: 'font/size/lg', type: 'FLOAT', value: Math.round(baseFontSize * designSystem.typeScaleRatio) },
            { name: 'font/size/xl', type: 'FLOAT', value: Math.round(baseFontSize * Math.pow(designSystem.typeScaleRatio, 2)) },
            { name: 'font/size/2xl', type: 'FLOAT', value: Math.round(baseFontSize * Math.pow(designSystem.typeScaleRatio, 3)) },
            { name: 'font/family/heading', type: 'STRING', value: designSystem.headingFont },
            { name: 'font/family/body', type: 'STRING', value: designSystem.fontFamily },
            { name: 'border-radius/base', type: 'FLOAT', value: borderRadius },
            { name: 'border-radius/sm', type: 'FLOAT', value: Math.max(0, borderRadius - 4) },
            { name: 'border-radius/lg', type: 'FLOAT', value: borderRadius + 4 },
          ],
        },
      ],
    }, null, 2);
  };

  const generateReactPackage = () => {
    const { primaryColor, secondaryColor, neutralColor, successColor, warningColor, errorColor, baseFontSize, typeScaleRatio, baseSpacing, borderRadius, fontFamily, headingFont } = designSystem;
    return `// Design Tokens - Generated by Design System Generator
// Project: ${designSystem.projectName}

export const colors = {
  primary: '${primaryColor}',
  secondary: '${secondaryColor}',
  neutral: '${neutralColor}',
  success: '${successColor}',
  warning: '${warningColor}',
  error: '${errorColor}',
} as const;

export const typography = {
  fontFamily: {
    heading: '${headingFont}',
    body: '${fontFamily}',
  },
  fontSize: {
    xs: ${Math.round(baseFontSize / Math.pow(typeScaleRatio, 2))}px,
    sm: ${Math.round(baseFontSize / typeScaleRatio)}px,
    base: ${baseFontSize}px,
    lg: ${Math.round(baseFontSize * typeScaleRatio)}px,
    xl: ${Math.round(baseFontSize * Math.pow(typeScaleRatio, 2))}px,
    '2xl': ${Math.round(baseFontSize * Math.pow(typeScaleRatio, 3))}px,
    '3xl': ${Math.round(baseFontSize * Math.pow(typeScaleRatio, 4))}px,
  },
} as const;

export const spacing = {
  base: ${baseSpacing}px,
  xs: ${baseSpacing * 0.5}px,
  sm: ${baseSpacing}px,
  md: ${baseSpacing * 2}px,
  lg: ${baseSpacing * 3}px,
  xl: ${baseSpacing * 4}px,
  '2xl': ${baseSpacing * 6}px,
  '3xl': ${baseSpacing * 8}px,
} as const;

export const borderRadius = {
  sm: ${Math.max(0, borderRadius - 4)}px,
  md: ${borderRadius}px,
  lg: ${borderRadius + 4}px,
  xl: ${borderRadius + 8}px,
  full: 9999px,
} as const;

export const tokens = {
  colors,
  typography,
  spacing,
  borderRadius,
} as const;

export default tokens;
`;
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 50,
        backgroundColor: 'rgba(0,0,0,0.5)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: '24px',
      }}
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div style={{
        backgroundColor: 'var(--card)',
        borderRadius: '16px',
        border: '1px solid var(--border)',
        width: '100%',
        maxWidth: '560px',
        boxShadow: '0 25px 50px rgba(0,0,0,0.15)',
      }}>
        {/* Header */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '20px 24px',
          borderBottom: '1px solid var(--border)',
        }}>
          <div>
            <h2 style={{ margin: 0, fontSize: '18px', fontWeight: '700', color: 'var(--foreground)' }}>
              Export Design Tokens
            </h2>
            <p style={{ margin: 0, fontSize: '13px', color: 'var(--muted-foreground)', marginTop: '2px' }}>
              Download your tokens in different formats
            </p>
          </div>
          <button
            onClick={onClose}
            style={{
              width: '32px', height: '32px', borderRadius: '8px',
              border: '1px solid var(--border)', backgroundColor: 'transparent',
              color: 'var(--foreground)', cursor: 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}
          >
            <X size={16} />
          </button>
        </div>

        {/* Content */}
        <div style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Figma Variables */}
          <div style={{
            padding: '20px',
            borderRadius: '12px',
            border: '1px solid var(--border)',
            backgroundColor: 'var(--background)',
          }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px' }}>
              <div style={{
                width: '44px', height: '44px', borderRadius: '10px',
                background: 'linear-gradient(135deg, #8d1ff4, #a855f7)',
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
              }}>
                <FileJson size={22} color="#fff" />
              </div>
              <div style={{ flex: 1 }}>
                <h3 style={{ margin: 0, fontSize: '15px', fontWeight: '600', color: 'var(--foreground)' }}>
                  Figma Variables
                </h3>
                <p style={{ margin: '4px 0 12px', fontSize: '13px', color: 'var(--muted-foreground)' }}>
                  Import directly into Figma as variable collections with light/dark modes
                </p>
                <button
                  onClick={() => downloadFile(generateFigmaVariables(), `${designSystem.projectName.toLowerCase().replace(/\s+/g, '-')}-figma-variables.json`, 'application/json')}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '6px',
                    padding: '8px 16px', borderRadius: '8px', border: 'none',
                    backgroundColor: 'var(--primary)', color: '#FFFFFF',
                    fontSize: '13px', fontWeight: '600', cursor: 'pointer',
                    fontFamily: 'var(--font-sans)',
                  }}
                >
                  <Download size={14} />
                  Download Figma Variables
                </button>
              </div>
            </div>
          </div>

          {/* React Package */}
          <div style={{
            padding: '20px',
            borderRadius: '12px',
            border: '1px solid var(--border)',
            backgroundColor: 'var(--background)',
          }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px' }}>
              <div style={{
                width: '44px', height: '44px', borderRadius: '10px',
                background: 'linear-gradient(135deg, #3B82F6, #06B6D4)',
                display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
              }}>
                <Package size={22} color="#fff" />
              </div>
              <div style={{ flex: 1 }}>
                <h3 style={{ margin: 0, fontSize: '15px', fontWeight: '600', color: 'var(--foreground)' }}>
                  React / TypeScript Package
                </h3>
                <p style={{ margin: '4px 0 12px', fontSize: '13px', color: 'var(--muted-foreground)' }}>
                  Ready-to-use TypeScript module with typed token exports for your React project
                </p>
                <button
                  onClick={() => downloadFile(generateReactPackage(), `${designSystem.projectName.toLowerCase().replace(/\s+/g, '-')}-tokens.ts`, 'text/plain')}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '6px',
                    padding: '8px 16px', borderRadius: '8px', border: 'none',
                    backgroundColor: '#3B82F6', color: '#FFFFFF',
                    fontSize: '13px', fontWeight: '600', cursor: 'pointer',
                    fontFamily: 'var(--font-sans)',
                  }}
                >
                  <Download size={14} />
                  Download React Package
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div style={{
          padding: '16px 24px',
          borderTop: '1px solid var(--border)',
          display: 'flex',
          justifyContent: 'flex-end',
        }}>
          <button
            onClick={onClose}
            style={{
              padding: '8px 20px', borderRadius: '8px',
              border: '1px solid var(--border)', backgroundColor: 'transparent',
              color: 'var(--foreground)', cursor: 'pointer',
              fontSize: '14px', fontWeight: '500', fontFamily: 'var(--font-sans)',
            }}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
